name: CI
on: [push, repository_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: cancelling
      uses: andymckay/cancel-action@master
    - name: Something slow
      run: |
        echo 'Try to cancel me, I dare you'
        sleep 360
        echo 'Finished sleeping'
 
 
